name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - feature/*

env:
    REGISTRY: ghcr.io

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      application: ${{ steps.set-apps.outputs.application }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set apps
        id: set-apps
        run: |
          # Проверяем существование папки ./cmd/
          if [ ! -d "./cmd" ]; then
            echo "Error: Directory ./cmd does not exist."
            exit 1
          fi

          # Используем find для получения только директорий в ./cmd/, преобразуем результат в строку через пробелы
          dirs=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)

          # Проверяем, что список не пустой
          if [ -z "$dirs" ]; then
            echo "Error: No directories found in ./cmd/"
            exit 1
          fi

          # Удаляем символы возврата каретки (\r) и преобразуем в строку через пробелы
          dirs=$(echo "$dirs" | tr '\r' ' ' | tr '\n' ' ')
          dirs=$(echo "$dirs" | sed 's/[[:space:]]*$//')
          # Преобразуем в json
          dirs=$(echo "$dirs" | jq -R 'split(" ")')
          dirs=$(echo "$dirs" | tr '\r' ' ' | tr '\n' ' ')
          dirs=$(echo "$dirs" | sed 's/[[:space:]]*$//')
          # Записываем результат в переменную окружения
          echo "application=$dirs" >> $GITHUB_OUTPUT
  ci:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        application: ${{ fromJSON(needs.define-matrix.outputs.application) }}
        # не собираем приложение pool
        # exclude:
        #   - application: pool
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Логин в Docker Registry (выполняется только для событий, кроме pull_request)
      - name: Login to Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CI_TOKEN }}

      # Создаем метаданные и строим образы для каждого приложения
      - name: Build and push $dir
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployments/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.application }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.application }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.application }}:v${{ github.ref_name }}
          labels: org.opencontainers.image.source=${{ github.repository }}
          build-args: APPLICATION_NAME=${{ matrix.application }}