name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feature/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Meta api
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/variegate-app/api
      - name: Meta pool
        id: meta-pool
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/variegate-app/tg-pool
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.CI_TOKEN }}
      - name: Build api
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployments/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          build-args: APPLICATION_NAME=api
      - name: Build pool
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployments/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-pool.outputs.tags }}
          labels: ${{ steps.meta-pool.outputs.labels }}
          build-args: APPLICATION_NAME=pool